#################################################
#				Makefile for lib				#
#					ø‚¥˙¬Î±‡“Î					#
#################################################

final_obj	=	../bin/lib.o

cpp_objs	=	
cc_objs		=	string.c.o
asm_objs	=

sinclude ../make.inc