#################################################
#				Makefile for lib				#
#					¿â´úÂë±àÒë					#
#################################################

final_obj	=	../bin/lib.o

cpp_objs	=	
cc_objs		=	string.c.o list.c.o
asm_objs	=	string.s.o

sinclude ../make.inc