#################################################
#				Makefile for arch				#
#				 Ó²¼þ²ã´úÂë±àÒë					#
#################################################

final_obj	=	../bin/arch.o

cpp_objs	=
cc_objs		=	kernel.c.o			\
				desc.c.o	gdt.c.o
asm_objs	=	start.s.o

sinclude ../make.inc