#################################################
#				Makefile for arch				#
#				 Ó²¼ş²ã´úÂë±àÒë					#
#################################################

final_obj	=	../bin/arch.o

cpp_objs	=
cc_objs		=	kernel.c.o			\
				desc.c.o			\
				table_gdt.c.o table_ldt.c.o table_idt.c.o \
				tss.c.o
asm_objs	=	start.s.o print.s.o

sinclude ../make.inc