#################################################
#			Makefile for micro-kernel			#
#				 Î¢ÄÚºË´úÂë±àÒë					#
#################################################

final_obj	=	../bin/micro-kernel.o

cpp_objs	=	
cc_objs		=	main.c.o handle.c.o init.c.o message.c.o thread.c.o vector.c.o \
				phypage.c.o	\
				mod_time.c.o mod_pubmsg.c.o
asm_objs	=	handle.s.o thread.s.o

sinclude ../make.inc