#################################################
#			Makefile for micro-kernel			#
#				 Î¢ÄÚºË´úÂë±àÒë					#
#################################################

final_obj	=	../bin/micro-kernel.o

cpp_objs	=	
cc_objs		=	kernel.c.o module.c.o thread.c.o message.c.o
asm_objs	=

sinclude ../make.inc