#################################################
#			Makefile for micro-kernel			#
#				 Î¢ÄÚºË´úÂë±àÒë					#
#################################################

final_obj	=	../bin/micro-kernel.o

cpp_objs	=	
cc_objs		=	kernel.c.o module.c.o thread.c.o message.c.o handle.c.o msg.c.o init.c.o
asm_objs	=	excp.s.o intr.s.o save.s.o

sinclude ../make.inc